"""The ontology modeling guide the CLI writes into a git-synced checkout.

``ontology_design_guide.md`` in this package is a byte-for-byte copy of the
canonical ``docs/ontology-design-guide.md`` (a repo-root test enforces they stay
identical — the backend image doesn't ship ``docs/``, so the CLI carries its own
copy). ``pull`` writes it into the checkout as ``<base_path>/AGENTS.md`` and
``fmt`` keeps it canonical, so a repo-aware agent loads current Cassis modeling
doctrine by convention. The file is managed: a banner marks it generated and the
CLI overwrites local edits, exactly as ``fmt`` rewrites drifted ontology YAML.

Two writers manage the file — this CLI and the Cassis server's git export — and
they may run different doctrine versions (the guide ships inside each). The
banner stamps its ``DOCTRINE_VERSION`` so an older CLI never *downgrades* a
guide a newer writer produced: ``refresh_guide`` leaves a newer-stamped file in
place and the CLI tells the user to upgrade instead.

``AGENTS.md`` sits inside the ontology base path but is never part of the
ontology tree — ``collect_files`` globs only ``*.yml`` / ``*.yaml``, so check,
fmt-of-YAML, upload, and pull-prune all ignore it.
"""

from __future__ import annotations

import re
from importlib import resources
from pathlib import Path
from typing import Literal

GUIDE_FILENAME = "AGENTS.md"

# Monotonic version of the doctrine text below. Bump it whenever
# ontology_design_guide.md changes (a backend test enforces the pairing) — it
# is what lets an older writer recognize a newer guide and leave it alone.
DOCTRINE_VERSION = 1

# Must stay byte-identical to backend/app/services/ontology_guide.py::_BANNER —
# the server-side git export writes the same file, and differing banners would
# make the two writers churn the file against each other.
_BANNER = (
    "<!--\n"
    f"Generated by Cassis — the ontology modeling guide (doctrine v{DOCTRINE_VERSION}).\n"
    "Do NOT edit: Cassis and cassis-cli (`ontology pull` / `ontology fmt`) overwrite this file.\n"
    "-->\n\n"
)

_DOCTRINE_VERSION_RE = re.compile(r"doctrine v(\d+)\b")

GuideStatus = Literal["current", "stale", "newer", "missing"]


def canonical_guide() -> str:
    """Return the managed ``AGENTS.md`` content: banner + the packaged guide."""
    body = resources.files("cassis_cli").joinpath("ontology_design_guide.md").read_text(encoding="utf-8")
    return _BANNER + body


def guide_status(ontology_dir: Path) -> GuideStatus:
    """Classify ``<ontology_dir>/AGENTS.md`` against the guide this CLI carries.

    - ``current``: byte-identical to what this CLI would write.
    - ``newer``: stamped with a higher doctrine version (written by a newer
      CLI or by the Cassis server) — must not be overwritten by this CLI.
    - ``stale``: anything else that exists (older doctrine, local edits, or an
      unversioned banner).
    - ``missing``: absent or unreadable.
    """
    try:
        existing = (ontology_dir / GUIDE_FILENAME).read_text(encoding="utf-8")
    except OSError:
        return "missing"
    if existing == canonical_guide():
        return "current"
    # Only a leading banner comment carries the stamp — the guide body may
    # legitimately mention "doctrine vN" as prose, and a hand-written file has
    # no banner at all. Both must read as "stale", never as "newer" (which is
    # never repaired and nags the user to upgrade a CLI that is already current).
    if existing.lstrip().startswith("<!--") and "-->" in existing:
        match = _DOCTRINE_VERSION_RE.search(existing.split("-->", 1)[0])
        if match is not None and int(match.group(1)) > DOCTRINE_VERSION:
            return "newer"
    return "stale"


def refresh_guide(ontology_dir: Path) -> GuideStatus:
    """Bring ``<ontology_dir>/AGENTS.md`` up to this CLI's doctrine, never down.

    Writes the managed guide when the file is ``stale`` or ``missing``; leaves
    ``current`` and ``newer`` files untouched. Returns the status found before
    writing, so the caller can report what happened (and nudge an upgrade on
    ``newer``). Raises OSError on a local write failure (the caller maps it to
    a usage-level exit).
    """
    status = guide_status(ontology_dir)
    if status in ("stale", "missing"):
        ontology_dir.mkdir(parents=True, exist_ok=True)
        (ontology_dir / GUIDE_FILENAME).write_text(canonical_guide(), encoding="utf-8")
    return status
